server.port=8083
spring.datasource.url=jdbc:postgresql://localhost:5432/user-service-db?currentSchema=rating-db&sslmode=disable
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
