server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/user-service-db?currentSchema=user-db&sslmode=disable
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver


#Retry Logic
resilience4j.retry.instances.ratingRetry.max-attempts=3
resilience4j.retry.instances.ratingRetry.wait-duration=1s
resilience4j.retry.instances.ratingRetry.enable-exponential-backoff=true
resilience4j.retry.instances.ratingRetry.exponential-backoff-multiplier=2

resilience4j.retry.instances.ratingRetry.retry-exceptions[0]=java.lang.Exception
resilience4j.retry.instances.ratingRetry.ignore-exceptions[0]=com.devaritra.user.service.exception.ResourceNotFoundException
